import React from "react";
import { IconType } from "react-icons";
import { FaGlassMartiniAlt, FaTelegramPlane } from "react-icons/fa";
import {
  FaAddressBook,
  FaAngleDown,
  FaArrowRightToBracket,
  FaArrowUpRightFromSquare,
  FaBars,
  FaBook,
  FaBug,
  FaCaretDown,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaCoins,
  FaEnvelopeOpen,
  FaFaceSmile,
  FaFigma,
  FaGithub,
  FaHandHoldingDroplet,
  FaInstagram,
  FaJoint,
  FaLaptopFile,
  FaLinkedin,
  FaLocationDot,
  FaPaw,
  FaPhone,
  FaRegChessKnight,
  FaRegCopy,
  FaRegFaceMeh,
  FaRegFaceSadTear,
  FaRegFaceSmile,
  FaRegFileLines,
  FaRuler,
  FaSmoking,
  FaTelegram,
  FaUser,
  FaUserPen,
  FaWallet,
  FaXTwitter,
  FaYoutube,
} from "react-icons/fa6";
import { GiRingBox } from "react-icons/gi";
import { HiOutlineLogout } from "react-icons/hi";
import {
  HiAdjustmentsHorizontal,
  HiArrowLongRight,
  HiArrowTopRightOnSquare,
  HiChevronDoubleLeft,
  HiChevronDoubleRight,
  HiEllipsisVertical,
  HiMiniCheckBadge,
  HiMiniClock,
  HiMiniExclamationTriangle,
  HiOutlineBookOpen,
  HiOutlineCake,
  HiOutlineCheckBadge,
  HiOutlineDocumentText,
  HiOutlineHeart,
  HiOutlineHome,
  HiOutlineInformationCircle,
  HiOutlineLanguage,
  HiOutlinePlusCircle,
  HiOutlineUser,
} from "react-icons/hi2";
import { ImSpinner6 } from "react-icons/im";
import { IoMagnet } from "react-icons/io5";
import { LuDot, LuGraduationCap, LuVenetianMask } from "react-icons/lu";
import {
  MdOutlineBloodtype,
  MdOutlineDashboard,
  MdOutlineFastfood,
  MdOutlineLocationOn,
  MdOutlinePeople,
  MdOutlineVerified,
  MdOutlineWorkOutline,
  MdVerified,
} from "react-icons/md";
import { RiPinDistanceLine, RiRobot2Line } from "react-icons/ri";
import {
  TbZodiacAquarius,
  TbZodiacAries,
  TbZodiacCancer,
  TbZodiacCapricorn,
  TbZodiacGemini,
  TbZodiacLeo,
  TbZodiacLibra,
  TbZodiacPisces,
  TbZodiacSagittarius,
  TbZodiacScorpio,
  TbZodiacTaurus,
  TbZodiacVirgo,
} from "react-icons/tb";
interface DynamicIconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  className?: string;
}

const iconComponents: Record<string, IconType> = {
  FaAddressBook,
  FaArrowRightToBracket,
  FaArrowUpRightFromSquare,
  FaAngleDown,
  FaBars,
  FaCaretDown,
  FaChevronLeft,
  FaChevronRight,
  FaFaceSmile,
  FaRegFaceSmile,
  FaRegCopy,
  FaRegChessKnight,
  FaEnvelopeOpen,
  FaFigma,
  FaGithub,
  FaHandHoldingDroplet,
  FaInstagram,
  FaLaptopFile,
  FaLinkedin,
  FaLocationDot,
  FaPhone,
  FaRegFileLines,
  FaUser,
  FaTelegram,
  FaXTwitter,
  FaYoutube,
  FaBug,
  FaTelegramPlane,
  HiOutlinePlusCircle,
  HiOutlineCheckBadge,
  HiChevronDoubleLeft,
  HiChevronDoubleRight,
  HiOutlineInformationCircle,
  HiOutlineLogout,
  HiOutlineHeart,
  FaWallet,
  FaChevronDown,
  HiEllipsisVertical,
  LuDot,
  HiArrowLongRight,
  HiOutlineDocumentText,
  FaRegFaceMeh,
  FaRegFaceSadTear,
  HiMiniExclamationTriangle,
  HiArrowTopRightOnSquare,
  HiMiniClock,
  HiMiniCheckBadge,
  HiAdjustmentsHorizontal,
  RiRobot2Line,
  MdOutlineDashboard,
  MdOutlinePeople,
  FaCoins,
  ImSpinner6,
  FaUserPen,
  MdVerified,
  HiOutlineCake,
  HiOutlineUser,
  IoMagnet,
  FaRuler,
  MdOutlineLocationOn,
  MdOutlineFastfood,
  FaGlassMartiniAlt,
  FaSmoking,
  FaJoint,
  FaPaw,
  MdOutlineWorkOutline,
  FaBook,
  HiOutlineBookOpen,
  HiOutlineHome,
  GiRingBox,
  LuGraduationCap,
  HiOutlineLanguage,
  TbZodiacAquarius,
  TbZodiacAries,
  TbZodiacCancer,
  TbZodiacCapricorn,
  TbZodiacGemini,
  TbZodiacLeo,
  TbZodiacLibra,
  TbZodiacPisces,
  TbZodiacSagittarius,
  TbZodiacScorpio,
  TbZodiacTaurus,
  TbZodiacVirgo,
  LuVenetianMask,
  RiPinDistanceLine,
  MdOutlineVerified,
  MdOutlineBloodtype,
};

const Icon: React.FC<DynamicIconProps> = ({ name, ...rest }) => {
  // Get the corresponding icon component based on the name
  const IconComponent = iconComponents[name];

  if (!IconComponent) {
    console.error(`Icon '${name}' not found`);
    return null;
  }

  return <IconComponent {...rest} />;
};

export default Icon;
